[fix] ace2_inner.js: Do fn+delete customly
storytouch/etherpad-lite pull request #6
Opened 2021-11-03 13:28 UTC by vitmf

'fn+delete' (or 'delete' in PCs) behaviour is inconsistent across browsers. In Chrome,
it might remove the class of the text in the line below when using
fn+delete to join lines. In this PR, we solve this issue by
doing 'fn+delete' customly, as we do 'delete' (or 'backspace' in PCs) customly.

Implements [card 2813](https://trello.com/c/zEnL8bT6/2813-coment%C3%A1rios-delete-em-uma-linha-anterior-remove-coment%C3%A1rio-da-pr%C3%B3xima-linha)

2021-11-04 13:39 UTC, WillianGoncalves requested changes
Deixei algumas sugestões. Teria que testar pra garantir que não quebra nada.

2021-11-04 13:39 UTC, WillianGoncalves commented on src/static/js/ace2_inner.js
> +
Essa linha deve ter sido apagada por engano.

2021-11-04 13:39 UTC, WillianGoncalves commented on src/static/js/ace2_inner.js
> +          if (nextLineEntry) {
```suggestion
          if (nextLineEntry) {
            const nextLineMarker = nextLineEntry.lineMarker;
```

2021-11-04 13:39 UTC, WillianGoncalves commented on src/static/js/ace2_inner.js
> +            }
```suggestion
            const shouldBeDeleted = char => isWordChar(char) || char === ' ';
            // delete as many unicode "letters or digits" or spaces in a row as possible;
            while (shouldBeDeleted(char)) {
              deleteForwardTo++;
              char = rep.alltext.charAt(deleteForwardTo);
            }

```

2021-11-04 13:39 UTC, WillianGoncalves commented on src/static/js/ace2_inner.js
> +    // separated. If it returns null, it means that the list was not cut, try
```suggestion
    // separated. If it returns null, it means that the list was not cut, then try
```

2021-11-08 13:06 UTC, vitmf commented on src/static/js/ace2_inner.js
> +            }
Aqui queremos deletar uma sequência de caracteres (uma palavra por exemplo) ou uma sequência de espaços, mas não uma sequência de caracteres e espaços juntos, por isso que  tratamos os casos separadamente.

2021-11-19 14:39 UTC, merged